### ISSUE TITLE
Using host memory and HYPRE_SetMemoryLocation(HYPRE_MEMORY_HOST) with CUDA enabled

### ISSUE THREAD

**Issue by jamtrott** [hypre-space/hypre#586]
Hi!

I have built hypre 2.23.0 with CUDA support. I am wondering if it is supported to set `HYPRE_SetMemoryLocation(HYPRE_MEMORY_HOST)` and to supply host-side pointers in calls to `HYPRE_IJMatrixSetValues` and `HYPRE_IJVectorSetValues`? I am unsure if this is expected to work, but then again I did not find anything in the documentation to indicate that it should not work.

At the moment, it seems to crash in a call to `HYPRE_PCGSolve`. Here is the full output from `gdb`, including the stack backtrace:

```
$ libtool --mode=execute mpirun -np 1 gdb -ex run --args ./_build_dgx2q/hyprep --verbose --verbose --mesh-size 100
GNU gdb (GDB) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./_build_dgx2q/hyprep...
Starting program: /home/james/src/benchmarks/hyprep/_build_dgx2q/hyprep --verbose --verbose --mesh-size 100
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x15553cb33700 (LWP 39517)]
[New Thread 0x155535f49700 (LWP 39518)]
[New Thread 0x155525ded700 (LWP 39532)]
[New Thread 0x1555204ab700 (LWP 39552)]
[New Thread 0x15552fbf9700 (LWP 39556)]
assemble: 0.003741 seconds
solve:

 Num MPI tasks = 1

 Num OpenMP threads = 1


BoomerAMG SETUP PARAMETERS:

 Max levels = 25
 Num levels = 3

 Strength Threshold = 0.250000
 Interpolation Truncation Factor = 0.000000
 Maximum Row Sum Threshold for Dependency Weakening = 0.900000

 Coarsening Type = PMIS

 No. of levels of aggressive coarsening: 5

 measures are determined locally


 No global partition option chosen.


Operator Matrix Information:

             nonzero            entries/row          row sums
lev    rows  entries sparse   min  max     avg      min         max
======================================================================
  0      99      295  0.030     2    3     3.0   0.000e+00   2.533e+02
  1      22       64  0.132     2    3     2.9  -2.842e-14   2.533e+02
  2       4       10  0.625     2    3     2.5   1.208e-13   6.333e+01


Interpolation Matrix Information:
                    entries/row        min        max            row sums
lev  rows x cols  min  max  avgW     weight      weight       min         max
================================================================================
  0    99 x 22      1    2   1.7   2.500e-01   1.000e+00   5.000e-01   1.000e+00
  1    22 x 4       1    2   1.4   2.500e-01   1.000e+00   2.500e-01   1.000e+00


     Complexity:    grid = 1.262626
                operator = 1.250847
                memory = 1.871186




BoomerAMG SOLVER PARAMETERS:

  Maximum number of cycles:         1
  Stopping Tolerance:               0.000000e+00
  Cycle type (1 = V, 2 = W, etc.):  1

  Relaxation Parameters:
   Visiting Grid:                     down   up  coarse
            Number of sweeps:            1    1     1
   Type 0=Jac, 3=hGS, 6=hSGS, 9=GE:     18   18     9
   Point types, partial sweeps (1=C, -1=F):
                  Pre-CG relaxation (down):   0
                   Post-CG relaxation (up):   0
                             Coarsest grid:   0

terminate called after throwing an instance of 'thrust::system::system_error'
  what():  reduce failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
--Type <RET> for more, q to quit, c to continue without paging--

Thread 1 "hyprep" received signal SIGABRT, Aborted.
0x000015554fff2fb7 in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x000015554fff2fb7 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x000015554fff4921 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x0000155541f95957 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x0000155541f9bae6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x0000155541f9bb21 in std::terminate() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x0000155541f9bd54 in __cxa_throw ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00001555523d84c5 in thrust::cuda_cub::throw_on_error (
    status=cudaErrorIllegalAddress,
    msg=0x15555290788c "reduce failed to synchronize")
    at /global/D1/homes/james/ex3modules/dgx2q/1.0.0/pkgs/cuda-toolkit-10.1.243/include/thrust/system/cuda/detail/util.h:213
#7  0x0000155552620afa in thrust::cuda_cub::detail::reduce_n_impl<thrust::detail::execute_with_allocator<hypre_device_allocator&, thrust::cuda_cub::execute_on_stream_base>, thrust::cuda_cub::transform_pair_of_input_iterators_t<double, double*, double*, thrust::multiplies<double> >, long, double, thrust::plus<double> >
    (binary_op=..., init=0, num_items=99, first=..., policy=...)
    at /global/D1/homes/james/ex3modules/dgx2q/1.0.0/pkgs/cuda-toolkit-10.1.243/include/thrust/system/cuda/detail/reduce.h:982
#8  thrust::cuda_cub::reduce_n<thrust::detail::execute_with_allocator<hypre_device_allocator&, thrust::cuda_cub::execute_on_stream_base>, thrust::cuda_cub::transform_pair_of_input_iterators_t<double, double*, double*, thrust::multiplies<dou--Type <RET> for more, q to quit, c to continue without paging--
ble> >, long, double, thrust::plus<double> > (policy=..., first=...,
    num_items=99, init=0, binary_op=...)
    at /global/D1/homes/james/ex3modules/dgx2q/1.0.0/pkgs/cuda-toolkit-10.1.243/include/thrust/system/cuda/detail/reduce.h:1017
#9  0x00001555526208da in thrust::cuda_cub::inner_product<thrust::detail::execute_with_allocator<hypre_device_allocator&, thrust::cuda_cub::execute_on_stream_base>, double*, double*, double, thrust::plus<double>, thrust::multiplies<double> > (policy=..., first1=0x55556899cc60, last1=0x55556899cf78,
    first2=0x55556899cc60, init=0, reduce_op=..., product_op=...)
    at /global/D1/homes/james/ex3modules/dgx2q/1.0.0/pkgs/cuda-toolkit-10.1.243/include/thrust/system/cuda/detail/inner_product.h:63
#10 0x000015555262081e in thrust::cuda_cub::inner_product<thrust::detail::execute_with_allocator<hypre_device_allocator&, thrust::cuda_cub::execute_on_stream_base>, double*, double*, double> (policy=..., first1=0x55556899cc60,
    last1=0x55556899cf78, first2=0x55556899cc60, init=0)
    at /global/D1/homes/james/ex3modules/dgx2q/1.0.0/pkgs/cuda-toolkit-10.1.243/include/thrust/system/cuda/detail/inner_product.h:81
#11 0x0000155552620718 in thrust::inner_product<thrust::detail::execute_with_allocator<hypre_device_allocator&, thrust::cuda_cub::execute_on_stream_base>, double*, double*, double> (exec=..., first1=0x55556899cc60, last1=0x55556899cf78,
    first2=0x55556899cc60, init=0)
    at /global/D1/homes/james/ex3modules/dgx2q/1.0.0/pkgs/cuda-toolkit-10.1.243/include/thrust/detail/inner_product.inl:46
--Type <RET> for more, q to quit, c to continue without paging--
#12 0x000015555261f076 in hypre_SeqVectorInnerProd (x=0x555568649be0,
    y=0x555568649be0) at vector.c:683
#13 0x00001555522949df in hypre_ParVectorInnerProd (x=0x555568649ba0,
    y=0x555568649ba0) at par_vector.c:410
#14 0x00001555521a3f6a in hypre_ParKrylovInnerProd (x=0x555568649ba0,
    y=0x555568649ba0) at par_krylov_func.c:175
#15 0x0000155552119170 in hypre_PCGSolve (pcg_vdata=0x55556899d4a0,
    A=0x55556a73ea60, b=0x555568649ba0, x=0x55556899d030) at pcg.c:348
#16 0x0000155552106756 in HYPRE_PCGSolve (solver=0x55556899d4a0,
    A=0x55556a73ea60, b=0x555568649ba0, x=0x55556899d030) at HYPRE_pcg.c:50
#17 0x000015555212b9ce in HYPRE_ParCSRPCGSolve (solver=0x55556899d4a0,
    A=0x55556a73ea60, b=0x555568649ba0, x=0x55556899d030)
    at HYPRE_parcsr_pcg.c:75
#18 0x000055555555857c in poisson1d_solve (amg_precond=true,
    amg_relax_type=18, amg_relax_order=0, amg_coarsen_type=8,
    amg_interp_type=18, amg_agg_num_levels=5, amg_agg_interp_type=7,
    amg_keep_transpose=true, amg_rap2=false, amg_num_sweeps=true,
    comm=<optimized out>, root=0, comm_size=<optimized out>,
    rank=<optimized out>, errcode=<synthetic pointer>, verbose=1,
    residualnorm=0x7ffffffee6a8, num_iterations=0x7ffffffee684,
    rtol=9.9999999999999998e-13, atol=0, max_iterations=10000,
    u=0x7ffffffee698, b=0x7ffffffee690, x=0x7ffffffee6a0, A=0x7ffffffee688)
    at ../src/hyprep.c:1986
--Type <RET> for more, q to quit, c to continue without paging--
#19 poisson1d (comm=<optimized out>, root=0, quiet=<optimized out>,
    errcode=<synthetic pointer>, rank=<optimized out>,
    comm_size=<optimized out>, verbose=<optimized out>, use_cuda=false,
    rtol=9.9999999999999998e-13, atol=0, max_iterations=10000,
    beta=6.2831853071795862, alpha=<optimized out>, right=<optimized out>,
    left=<optimized out>, mesh_size=<optimized out>) at ../src/hyprep.c:2086
#20 main (argc=<optimized out>, argv=<optimized out>) at ../src/hyprep.c:2346
```

Note that everything works just fine if I use a version of hypre without CUDA support, or if I set `HYPRE_SetMemoryLocation(HYPRE_MEMORY_DEVICE)` and supply device-side pointers to the data when calling `HYPRE_IJMatrixSetValues` and `HYPRE_IJVectorSetValues`.

I am using hypre 2.23.0 with the following configure options:
```
./configure --prefix=${PREFIX} \
    --enable-shared \
     --enable-debug \
    --with-blas-lib-dirs="${BLASDIR}" --with-blas-libs=openblas \
    --with-lapack-lib-dirs="${BLASDIR}" --with-lapack-libs=openblas \
    --with-MPI \
    --with-MPI-include="${MPI_HOME}/include" \
    --with-MPI-lib-dirs="${MPI_HOME}/lib" \
    --with-MPI-libs=mpi \
    --with-cuda \
    CUDA_HOME="${CUDA_TOOLKIT_ROOT}"
```

**Comment by victorapm** [comment]
@jamtrott, I apologize for not replying this before.

Currently, if hypre is built with CUDA support, then some linear algebra operations are assumed to run on the device. That causes issues when dealing with vectors that live on the host memory. We are working to solve this limitation. For now, you would need to build hypre without CUDA support to be able to use the solvers on the CPU.

**Comment by victorapm** [comment]
Closing this issue due to inactivity. Please, feel free to reopen if needed
