### ISSUE TITLE
boomeramg crash with openmp

### ISSUE THREAD

**Issue by bobby-philip** [hypre-space/hypre#60]
Hi:

I'm getting the following crash with hypre when I turn on OpenMP. I'm running hypre 2.18.2 compiled with intel, MPI is mpich, and OMP_NUM_THREADS=16 and I'm running on KNL's

hypre is configured with"
./configure --enable-mixedint --with-openmp

======= Backtrace: =========
(hypre_BoomerAMGSetup+0x26a2)[0x3982ef2]
double free or corruption (fasttop): 0x00000000056a6420 ***
free(): invalid next size (normal): 0x0000000006ad4f60 ***

gdb backtrace gives:

(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  <signal handler called>
#2  0x00002aaacd6521c2 in _int_free () from /lib64/libc.so.6
#3  0x0000000003a6533c in hypre_BoomerAMGCreateSHost (A=<optimized out>, strength_threshold=<error reading variable: Unable to access DWARF register number 67>, max_row_sum=0, num_functions=0, dof_func=0x0, S_ptr=<optimized out>) at par_strength.c:522
#4  hypre_BoomerAMGCreateS (A=0x2aaacd977640 <main_arena>, strength_threshold=0, max_row_sum=0, num_functions=0, dof_func=0x2c1030, S_ptr=0x0) at par_strength.c:554
#5  0x0000000003982ef2 in hypre_BoomerAMGSetup (amg_vdata=0x2aaacd977640 <main_arena>, A=0x0, f=0x2c1030, u=0x0) at par_amg_setup.c:988
#6  0x0000000003b66852 in hypre_PCGSetup (pcg_vdata=0x2aaacd977640 <main_arena>, A=0x0, b=0x2c1030, x=0x0) at pcg.c:219
#7  0x0000000003977a6c in hypre_parcsrpcgsetup_ (solver=0x2aaacd977640 <main_arena>, A=0x0, b=0x2c1030, x=0x0, ierr=0x792fa00) at F90_HYPRE_parcsr_pcg.c:64

**Comment by bobby-philip** [comment]
Hi, just following up to see if you would be willing to take a look at this. Thanks!

**Comment by ulrikeyang** [comment]
Hi,
How big is the problem you are running, and how many MPI tasks?
Thanks
Ulrike

**Comment by rfalgout** [comment]
Has this issue been resolved?  Thanks!  -Rob

**Comment by wuyeyanjiuyuan** [comment]
Has this issue been resolved? Thanks! -Qi
