### ISSUE TITLE
GPU version segfault

### ISSUE THREAD

**Issue by hokkanen** [hypre-space/hypre#88]
Hi,

I am trying to use Hypre GPU version but I am running into the following issue when calling **HYPRE_StructVectorSetConstantValues** from [Parflow](https://github.com/hokkanen/parflow/blob/89dfad6635d84e310b8271a41e749776b788aa39/pfsimulator/parflow_lib/pf_smg.c#L358). Everything works fine when compiling without the GPU support.

The HYPRE vector is created as follows:
```
 HYPRE_StructVectorCreate(MPI_COMM_WORLD, instance_xtra->hypre_grid, 
   &instance_xtra->hypre_x)); 
 HYPRE_StructVectorSetNumGhost(instance_xtra->hypre_x, full_ghosts); 
 HYPRE_StructVectorInitialize(instance_xtra->hypre_x); 
 HYPRE_StructVectorSetConstantValues(instance_xtra->hypre_x, 0.0e0);
```

GDB output:
```
Program received signal SIGSEGV, Segmentation fault.
BoxLoopforall<__nv_hdl_wrapper_t<false, false, __nv_dl_tag<int (*)(hypre_StructVector_struct*, double), &hypre_StructVectorSetConstantValues, 1u>, void (int), hypre_Boxloop_struct, double*, double> >(int, int, __nv_hdl_wrapper_t<false, false, __nv_dl_tag<int (*)(hypre_StructVector_struct*, double), &hypre_StructVectorSetConstantValues, 1u>, void (int), hypre_Boxloop_struct, double*, double>) (
    policy=0, length=length@entry=600000, loop_body=...)
    at _hypre_struct_mv.h:802
802	      HYPRE_CUDA_LAUNCH( forall_kernel, gDim, bDim, loop_body, length );
#0  BoxLoopforall<__nv_hdl_wrapper_t<false, false, __nv_dl_tag<int (*)(hypre_StructVector_struct*, double), &hypre_StructVectorSetConstantValues, 1u>, void (int), hypre_Boxloop_struct, double*, double> >(int, int, __nv_hdl_wrapper_t<false, false, __nv_dl_tag<int (*)(hypre_StructVector_struct*, double), &hypre_StructVectorSetConstantValues, 1u>, void (int), hypre_Boxloop_struct, double*, double>)
    (policy=0, length=length@entry=600000, loop_body=...)
    at _hypre_struct_mv.h:802
#1  0x00002aaaab0cb22c in hypre_StructVectorSetConstantValues ()
    at nvcc_internal_extended_lambda_implementation:420
#2  0x000000000049be99 in SMGInitInstanceXtra (problem=0x0, grid=0x0, 
    problem_data=0x46a5b10, pf_matrix=0x2aaaf2299200, temp_data=0x0)
    at /p/project/cesmtst/hokkanen1/pfdir/parflow/pfsimulator/parflow_lib/pf_smg.c:365
```

Any ideas?

Thanks,
Jaro

**Comment by liruipeng** [comment]
Hi, Jaro,
It seemed that `HYPRE_StructVectorSetConstantValues` worked fine in our struct interface test driver. Is there a way I can reproduce the segfault in Parflow on my end, if possible?  It will be very helpful

Thanks

-Ruipeng
